edition = "2018"
max_width = 102400
version = "Two"

control_brace_style = "ClosingNextLine"
merge_imports = true
use_small_heuristics = "Max"

[pest]
exclude = ["tests/**/*.pest", "tests/test.pest"]
