params    = { "something" }
arguments = {
    "(" ~ (params // bad comment0
  // bad comment0.1
  ~ ("," ~ params)* // bad comment1
  ~ ","?)? ~ ")"
}
blah      = {
    ("w") ~ &("z")
}

complex_expr = _{
    "a"
  | "b" ~ ("b1" | "b2" ~ "b3" | "b4")
  | "c"
  | "d" ~ "d1"
  | "e"
  | "f"
}

// https://github.com/pest-parser/pest-fmt/issues/15
log_line1 = {
    "0" ~ ("1" // a comment
  | "2" // another comment
  | "3" // longer comment
  | "4" // final comment
  | "a" | "b" | "c" | "d")
}

log_line2 = {
    "0" ~ ("0" // a comment
  | "0" // another comment
  | "1" // longer comment
  | "2" // final comment
  | "a" | "b" | "c" | "d" | "e")
}

log_line3 = {
    // lead comment
    "1" ~ ("2" // another comment
  | "3" // longer comment
  | "4" // final comment
  | "5" | "a" | "b" | "c" | "d" | "e") // comment
}